#!/bin/bash
#
# Create a FUGUE compatible fieldmap for EPI unwarping from multiecho phase reconstructed Siemens DICOM data
#
# SYNTAX: mkfmap <mag_dir> <phase_dir>
#
# ARGS:
# mag_dir = directory containing magnitude DICOM images from B0 field map
# phase_dir = directory containing phase DICOM images from B0 field map
#
# These directories should be generated automatically by the DICOM image server.
# If not, you'll have to sort out the phase and mag images some other way
#
# AUTHOR: Mike Tyszka, Ph.D.
# PLACE : Caltech
# DATES : 12/02/2008 JMT From scratch
#         05/11/2009 JMT Switch to single directory argument
#
# Copyright 2008,2009 California Institute of Technology. All rights reserved.

# Gradient echo time difference in ms
# This is standard for most Adolphslabs protocols but should be checked
TE=2.46

if [ $# -ne 2 ]
then
  echo "USAGE: mkfmap <mag_dir> <phase_dir>"
  exit
fi

magdir=$1
phidir=$2
fmapdir=`pwd`

echo Magnitude directory : $magdir
echo Phase directory     : $phidir

# Convert dual-echo GRE DICOM series to Nifti using mri_convert
echo Converting magnitude images
mri_convert $1 -i `ls ${magdir}/* | tail -n 1` -o ${fmapdir}/fmap_mag.nii.gz

# Average first and 2nd echoes
echo Averaging first and second echo
fslmaths ${fmapdir}/fmap_mag -Tmean ${fmapdir}/fmap_mag

# Skull strip mag image
echo Extract magnitude brain
bet ${fmapdir}/fmap_mag ${fmapdir}/fmap_mag_brain

echo Converting phase images
mri_convert $2 -i `ls ${phidir}/* | tail -n 1` -o ${fmapdir}/phi.nii.gz

# Scale phase image to radians
fslmaths ${fmapdir}/phi -sub 2048 -mul 3.1415926 -div 2048 ${fmapdir}/phi_rad -odt float

# Run PRELUDE phase unwrapping with magnitude trust region
echo Phase unwrapping fieldmap
prelude -a ${fmapdir}/fmap_mag -p ${fmapdir}/phi_rad -o ${fmapdir}/phi_rad_uw

# Scale unwrapped field map to rad/s
fslmaths ${fmapdir}/phi_rad_uw -mul 1000 -div $TE ${fmapdir}/fmap -odt float

# Regularize fieldmap
echo Regularizing fieldmap
fugue --loadfmap=${fmapdir}/fmap -m --savefmap=${fmapdir}/fmap
fugue --loadfmap=${fmapdir}/fmap -s 1 --savefmap=${fmapdir}/fmap

# Reorient to MNI
echo Reorienting to MNI
fslreorient2std ${fmapdir}/fmap ${fmapdir}/fmap
fslreorient2std ${fmapdir}/fmap_mag ${fmapdir}/fmap_mag
fslreorient2std ${fmapdir}/fmap_mag_brain ${fmapdir}/fmap_mag_brain

# Cleanup
echo Cleaning up
rm -rf ${fmapdir}/mag.nii.gz ${fmapdir}/phi*.nii.gz
