#!/bin/bash
#
# Create a FUGUE compatible fieldmap for EPI unwarping from multiecho phase reconstructed Siemens DICOM data
#
# SYNTAX: mkfmap <mag_dir> <phase_dir>
#
# ARGS:
# mag_dir = directory containing magnitude DICOM images from B0 field map
# phase_dir = directory containing phase DICOM images from B0 field map
#
# These directories should be generated automatically by the DICOM image server.
# If not, you'll have to sort out the phase and mag images some other way
#
# AUTHOR: Mike Tyszka, Ph.D.
# PLACE : Caltech
# DATES : 12/02/2008 JMT From scratch
#         05/11/2009 JMT Switch to single directory argument
#         09/29/2014 JMT Add command line TE argument
#
# Copyright 2014 California Institute of Technology. All rights reserved.

if [ $# -ne 4 ]
then
  echo "USAGE   : mkfmap <mag directory> <phase directory> <output directory> <echo time difference in ms>"
  echo "EXAMPLE : mkfmap Fieldmap_3 Fieldmap_4 Fieldmap 2.46"
  exit
fi

magdir=$1
phidir=$2
outdir=$3
dTE=$4

echo Magnitude directory  : $magdir
echo Phase directory      : $phidir
echo Output directory     : $outdir
echo Echo time difference : $dTE

# Convert dual-echo GRE DICOM series to Nifti using mri_convert
echo Converting magnitude images
mri_convert $1 -i `ls ${magdir}/* | tail -n 1` -o ${outdir}/fmap_mag.nii.gz

# Average first and 2nd echoes
echo Averaging first and second echo
fslmaths ${outdir}/fmap_mag -Tmean ${outdir}/fmap_mag

# Skull strip mag image
echo Extract magnitude brain
bet ${outdir}/fmap_mag ${outdir}/fmap_mag_brain

echo Converting phase images
mri_convert $2 -i `ls ${phidir}/* | tail -n 1` -o ${outdir}/phi.nii.gz

# Scale phase image to radians
fslmaths ${outdir}/phi -sub 2048 -mul 3.1415926 -div 2048 ${outdir}/phi_rad -odt float

# Run PRELUDE phase unwrapping with magnitude trust region
echo Phase unwrapping fieldmap
prelude -a ${outdir}/fmap_mag -p ${outdir}/phi_rad -o ${outdir}/phi_rad_uw

# Scale unwrapped field map to rad/s
fslmaths ${outdir}/phi_rad_uw -mul 1000 -div $dTE ${outdir}/fmap -odt float

# Regularize fieldmap
echo Regularizing fieldmap
fugue --loadfmap=${outdir}/fmap -m --savefmap=${outdir}/fmap
fugue --loadfmap=${outdir}/fmap -s 1 --savefmap=${outdir}/fmap

# Reorient to MNI
echo Reorienting to MNI
fslreorient2std ${outdir}/fmap ${outdir}/fmap
fslreorient2std ${outdir}/fmap_mag ${outdir}/fmap_mag
fslreorient2std ${outdir}/fmap_mag_brain ${outdir}/fmap_mag_brain

# Cleanup
echo Cleaning up
rm -rf ${outdir}/mag.nii.gz ${outdir}/phi*.nii.gz
