#!/bin/bash
#
# Use FSL and Freesurfer commands to 1. convert DICOM volumes to Nifti, then rigid body coregister volumes and average
# This script should be run in the directory containing the two or more DICOM T1 scan directories
#
# SYNTAX: mkT1avg <Output Stub> <DICOM directory list>
# EXAMPLE:
#   mkT1avg JMT_001 2 3 4 5 
# generates JMT_001.nii.gz from directories 2 3 4 and 5
#
# AUTHOR: Mike Tyszka
# PLACE : Caltech
# DATES : 01/09/2009 JMT From scratch

# First grab the output file stub
outfile=$1

# Lose arg 1 from $@
shift

# Init image counter
nim=0

# Init converted T1 file list
T1_files=""

# Loop over provided DICOM directories
for dcm_dir in "$@"
do
  echo "Converting $dcm_dir"
  nii=`dc2nii $dcm_dir`
  let "nim+=1"
  T1_files+="${nii} "
done

echo "Processed $nim images"

# Now flirt average the converted images
echo "flirt_average $nim ${T1_files} ${outfile}"
flirt_average $nim ${T1_files} ${outfile} -dof 6

# Reorient result to MNI-ish frame
echo "Reorienting to MNI-ish frame"
fslreorient2std ${outfile} ${outfile}

# Cleanup
echo "Cleaning up"
for dcm_dir in "$@"
do
  rm -rf ${dcm_dir}/*.nii.gz ${dcm_dir}/*.mat
done
