#!/bin/bash
#
# Create average T1 registered to MNI space from multiple T1 volumes
#
# SYNTAX: mkT1avg <Output Stub> <DICOM directory list>
# EXAMPLE:
#   mkT1avg JMT_001 2 3 4 5 
# generates JMT_001.nii.gz from directories 2 3 4 and 5
#
# AUTHOR: Mike Tyszka
# PLACE : Caltech
# DATES : 01/09/2009 JMT From scratch

# First grab the output file stub
stub=$1

# Lose arg 1 from $@
shift

# Loop over all remaining arguments
nim=0

for arg in "$@"
do
	echo "Converting $arg"
	let "nim+=1"
	dc2nii $arg $arg
done

echo "Processed $nim images"

# Now flirt average the converted images
echo "flirt_average $nim $@ $stub"
flirt_average $nim $@ $stub -FAref ${FSLDIR}/data/standard/MNI152_T1_2mm
